fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\Security\User
    group:
        group_class: AppBundle\Entity\Security\Group
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
